EXTRA_CFLAGS +=-Wno-error=date-time
EXTRA_CFLAGS +=-Wno-date-time

obj-$(CONFIG_TOUCHSCREEN_GT915)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT915)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT915)	+= goodix_tool.o
